name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Cache Pico SDK
      uses: actions/cache@v3
      with:
        path: ~/pico-sdk
        key: ${{ runner.os }}-pico-sdk-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-pico-sdk-
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib build-essential
    
    - name: Setup Pico SDK
      run: |
        if [ ! -d ~/pico-sdk ]; then
          git clone https://github.com/raspberrypi/pico-sdk.git ~/pico-sdk
          cd ~/pico-sdk
          git submodule update --init
        fi
        echo "PICO_SDK_PATH=$HOME/pico-sdk" >> $GITHUB_ENV
    
    - name: Create build directory
      run: mkdir build
    
    - name: Configure CMake
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: |
        cd build
        make -j$(nproc)
    
    - name: Check build artifacts
      run: |
        ls -la build/
        echo "Library built successfully:"
        ls -la build/libcap1188.a
        echo "Example built successfully:"
        ls -la build/basic_touch.uf2
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cap1188-build-${{ github.sha }}
        path: |
          build/*.uf2
          build/libcap1188.a
        retention-days: 30

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install clang-format
      run: sudo apt install -y clang-format
    
    - name: Check code formatting
      run: |
        find include src examples -name "*.hpp" -o -name "*.cpp" | xargs clang-format --dry-run --Werror